config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"

  get "tasks/:id", to: "tasks#show", as: "task"
  get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  post "tasks", to: "tasks#create"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(res_params)
    task.save

    redirect_to task_path(task)
  end

  def edit
  end

  def update
    task = Task.find(params[:id])
    task.update(res_params)

    redirect_to task_path(task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def res_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
<h1> New task</h1>

<%= form_with model: task do |t| %>
  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label"><%= t.label :title %>
  <%= t.text_field :title %>
  </label>
  </div>
  <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label"><%= t.label :details %>
  <%= t.text_field :details %>
  </label>
  </div>
  <%= t.submit %>
<% end %>
</div>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container margin-top-100" style="width: 600px;">
<h1 class="text-center p-5">My tasks</h1>
<ul class="list-group d-grid gap-3">
<% @tasks.each do |task| %>
  <h3>
  <li class="list-group-item p-3 bg-light border text-decoration-none" style="text-decoration:none;"><%= link_to task.title, task_path(task.id), class:"text-decoration-none" %></li>
  </h3>
<% end %>
</ul>
<p class="mt-100 text-end"><%= link_to "Create New Task", tasks_new_path %><p>
</div>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="container">
<div class="card">
<h1><%= @task.title %></h1>
<p>Details: <%= @task.details %></p>
</div>
<%= link_to "Back to list", tasks_path %>
<%= link_to "Edit the task", task_edit_path(@task.id) %>
<%= link_to "Delete the task", task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure"} %>
</div>